version: '3.8'

services:
  gateway:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ../gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
      - ui
  server:
    build: ../server
    ports:
      - "3200:3200"
    # volumes:
    #   - .:/server
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: birdsdb
      PGPASSWORD: example
      PORT: 3200
    depends_on:
      db:
        condition: service_healthy
  ui:
    build: ../ui
    ports:
      - "5173:5173"
    # volumes:
    #   - .:/ui
    depends_on:
      - db

  db:
    build: ../db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    # volumes:
    #   - ./db:/db
    environment:
      POSTGRES_PASSWORD: example
